spring.application.name=demo

# Database connection pointing to your 'users' schema (allowPublicKeyRetrieval=true ???????)
spring.datasource.url=jdbc:mysql://localhost:3306/users?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Custom IP and Port setup
server.port=8081
server.address=0.0.0.0

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true